/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a254d0e4-eb5a-41d1-83b9-ff7e6e2f6309",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nPY2jaRKl",
    "aws_user_pools_web_client_id": "14pp188ovdnekiqedhbo22of6c",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://x75hcd7xmverbcs3r3ac4rziba.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hgomuqn6yfhwrcla3cm3vhk5bm",
    "aws_user_files_s3_bucket": "avatar-upload32642-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
